# rvo_config.yaml
time_step: 0.033
neighbor_dist: 0.8 # 2 * max_speed * time_horizon + 2 * effective_radius
max_neighbors: 20
time_horizon: 3.3 # 応答遅延は？
time_horizon_obst: 3.3
robot_radius: 0.022 # 本体半径 0.035->0.042
wheel_distance: 0.025 #　車輪間隔
enlarge_distance: 0.032 # non-holonomic用偏移量 (0.042 + 0.01)
max_speed: 0.1
pos_threshold: 0.02
ang_threshold: 0.05
lv_limit: 0.1
w_limit: 3.14159  # Equivalent to np.pi